// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BooleanDisplay: typeof import('./theme/components/BooleanDisplay.vue')['default']
    DemoContainer: typeof import('./theme/components/DemoContainer.vue')['default']
    FunctionBadge: typeof import('./theme/components/FunctionBadge.vue')['default']
    FunctionInfo: typeof import('./theme/components/FunctionInfo.vue')['default']
    FunctionsList: typeof import('./theme/components/FunctionsList.vue')['default']
    Home: typeof import('./theme/components/Home.vue')['default']
    HomeFeatures: typeof import('./theme/components/HomeFeatures.vue')['default']
    HomeFooter: typeof import('./theme/components/HomeFooter.vue')['default']
    HomeHero: typeof import('./theme/components/HomeHero.vue')['default']
    LearnMoreComponents: typeof import('./theme/components/LearnMoreComponents.vue')['default']
    LearnMoreDirectives: typeof import('./theme/components/LearnMoreDirectives.vue')['default']
    Note: typeof import('./theme/components/Note.vue')['default']
    ReloadPrompt: typeof import('./theme/components/ReloadPrompt.vue')['default']
    RequiresProxy: typeof import('./theme/components/RequiresProxy.vue')['default']
    TeamMember: typeof import('./theme/components/TeamMember.vue')['default']
  }
}

export {}
